name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #
    strategy:
      matrix:
        node: [18, 20]

    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v3
      - name: Run linting rules and build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

      - name: Run tests and generate coverage
        run: |
          npm run test &&
          npm i coverage-badges-cli -g &&
          coverage-badges --output coverage/badges.svg

      - name: Run build
        run: npm run build
